### ISSUE TITLE
Histogram Ids must be trimmed

### ISSUE THREAD

**Issue by vstange** [ag-gipp/MathMLConverters#9]
In `MathMLConverter` all histogram ids are saved as `this.histogram.add(tmpNode.getTextContent());`.
This can lead to errors since the text content of a node can contain line breaks, tabs, white spaces, etc.

The Id must be trimmed before storing.

**Comment by physikerwelt** [comment]
@vstange you are right in theory. However, I think we should investigate the cases why spaces are generated in the first place. So we would better try to address the problem from its root. Please open a new bug with actual examples.
